
titan_mtp_uniform = ["USP_G3C_MC","USP_G3C_CU_MC","USP_G3C_MC","USP_G3C_CU_KP_MC","USP_G3C_CU_KP_MX_MC","USP_G3C_CU_KP_OR_MC","USP_G3C_CU_MX_MC",
"USP_G3C_CU_OR_MC","USP_G3C_KP_MC","USP_G3C_KP_OR_MC","USP_G3C_MX_MC","USP_G3C_OR_MC","USP_G3C_RS_CU_MC",
"USP_G3C_RS_CU_KP_OR_MC","USP_G3C_RS_CU_KP_OR_VQ_MC","USP_G3C_RS_CU_MX_MC","USP_G3C_RS_CU_MX_VQ_MC","USP_G3C_RS_CU_OR_MC",
"USP_G3C_RS_CU_OR_VQ_MC","USP_G3C_RS_CU_VQ_MC","USP_G3C_RS_KP_MC","USP_G3C_RS_KP_OR_MC","USP_G3C_RS_KP_OR_VQ_MC",
"USP_G3C_RS_KP_VQ_MC","USP_G3C_RS_MX_MC","USP_G3C_RS2_CU_KP_MC","USP_G3C_RS2_CU_KP_OR_MC","USP_G3C_RS2_CU_KP_VQ_MC","USP_G3C_RS2_KP_MC",
"USP_PCU_G3C_MC","USP_PCU_G3C_KP_MC","USP_PCU_G3C_KP_MX_MC_BLK","USP_PCU_G3C_KP_MX_MC_RGR","USP_PCU_G3C_KP_MX_MC","USP_SOFTSHELL_G3C_MC_BLK",
"USP_SOFTSHELL_G3C_MC_RGR","USP_SOFTSHELL_G3C_MC","USP_SOFTSHELL_G3C_KP_MC","USP_SOFTSHELL_G3C_KP_RGR_MC","USP_SOFTSHELL_G3C_KP_MX_MC"];

titan_jtp_uniform = ["USP_G3C_M81","USP_G3C_CU_M81","USP_G3C_CU_KP_M81","USP_G3C_CU_KP_MX_M81","USP_G3C_CU_MX_M81","USP_G3C_CU_OR_M81","USP_G3C_KP_M81","USP_G3C_KP_MX_M81",
"USP_G3C_MX_M81","USP_G3C_MX_VQ_M81","USP_G3C_OR_M81","USP_G3C_OR_VQ_M81","USP_G3C_RS_CU_M81","USP_G3C_RS_CU_KP_MX_VQ_M81","USP_G3C_RS_CU_KP_OR_M81","USP_G3C_RS_CU_KP_OR_VQ_M81",
"USP_G3C_RS_CU_KP_VQ_M81","USP_G3C_RS_CU_MX_VQ_M81","USP_G3C_RS_CU_OR_M81","USP_G3C_RS_CU_VQ_M81","USP_G3C_RS_KP_OR_VQ_M81","USP_G3C_RS_MX_M81","USP_G3C_RS_MX_VQ_M81","USP_G3C_RS_OR_M81",
"USP_G3C_RS_OR_VQ_M81","USP_G3C_RS2_M81","USP_G3C_RS2_CU_KP_M81","USP_G3C_RS2_KP_OR_M81","USP_G3C_RS2_KP_VQ_M81","USP_G3C_VQ_M81","USP_PCU_G3C_BLK_M81","USP_PCU_G3C_KP_MCT","USP_PCU_G3C_KP_OR_MCT",
"USP_SOFTSHELL_G3C_RGR_M81","USP_SOFTSHELL_G3C_KP_RGR_M81","USP_SOFTSHELL_G3C_KP_MX_RGR_M81"];


titan_wtp_uniform = ["USP_G3C_CU_GRY","USP_OVERWHITE_G3C_KP","USP_OVERWHITE_G3C_KP_MCA_GRY","USP_OVERWHITE_G3C_KP_MCA_MC","USP_OVERWHITE_G3C_KP_MCA_RGR","USP_OVERWHITE_G3C_KP_MX",
"USP_OVERWHITE_G3C_KP_OR_MCA_KHK","USP_OVERWHITE_G3C_KP_OR_MCA_MC","USP_OVERWHITE_G3C_OR","USP_PCU_G3C_GRY_MC","USP_PCU_G3C_MCA_GRY","USP_PCU_G3C_KP_MCA_GRY","USP_PCU_G3C_KP_MCA_MC",
"USP_PCU_G3C_KP_MX_MCA_GRY","USP_PCU_G3C_KP_MX_MCA_RGR","USP_PCU_G3C_KP_OR_MCA_MCB","USP_PCU_G3C_OR_MCA_BLK","USP_PCU_G3C_OR_MCA_GRY","USP_PCU_G3C_OR_MCA_MC"];


titan_mtp_westen = ["USP_CRYE_CPC_COMMS_BELT", "USP_CRYE_CPC_COMMS_BELT_MC", "USP_CRYE_CPC_COMMS_BELT_RGR", "USP_CRYE_CPC_LEAD_BELT", "USP_CRYE_CPC_LEAD_BELT_MC", "USP_CRYE_CPC_LEAD_BELT_RGR",
"USP_CRYE_JPC_ASLTB_CBR", "USP_CRYE_JPC_ASLTB", "USP_CRYE_JPC_ASLTB_RGR", "USP_CRYE_JPC_TLB_CBR", "USP_CRYE_JPC_TLB", "USP_CRYE_JPC_TLB_RGR",
"USP_CRYE_CPC_MEDIC_BELT", "USP_CRYE_CPC_MEDIC_BELT_MC", "USP_CRYE_CPC_MEDIC_BELT_RGR","USP_CRYE_CPC_WAEPON_BELT", "USP_CRYE_CPC_WAEPON_BELT_MC", "USP_CRYE_CPC_WAEPON_BELT_RGR",
"USP_CRYE_JPC_GRB_CBR",  "USP_CRYE_JPC_GRB", "USP_CRYE_JPC_RGR","USP_EAGLE_MBAV_LOAD_MC","USP_CRYE_JPC_MGB_CBR", "USP_CRYE_JPC_MGB", "USP_CRYE_JPC_MGB_RGR" ];

titan_jtp_westen = ["USP_CRYE_CPC_COMMS_BELT_RGR", "USP_CRYE_CPC_LEAD_BELT_RGR", "USP_CRYE_JPC_ASLTB_RGR", "USP_CRYE_JPC_TLB_RGR",
"USP_CRYE_CPC_MEDIC_BELT_RGR", "USP_CRYE_CPC_WAEPON_BELT_RGR", "USP_CRYE_JPC_RGR","USP_CRYE_JPC_MGB_RGR"];

titan_wtp_westen = ["USP_VEST_STRANDHOGG2_MCA","USP_EAGLE_MBAV_LOAD_MCA"];


titan_mtp_helm = ["USP_CRYE_AIRFRAME_CT3","USP_OPSCORE_FASTMTC_C","USP_OPSCORE_FASTMTC_CM","USP_OPSCORE_FASTMTC_CMW","USP_OPSCORE_FASTMTC_CMG","USP_OPSCORE_FASTMTC_CMGSW",
"USP_OPSCORE_FASTMTC_CMGTW","USP_OPSCORE_FASTMTC_CMSW","USP_OPSCORE_FASTMTC_CSW","USP_OPSCORE_FASTMTC_CBR_C","USP_OPSCORE_FASTMTC_CBR_CM","USP_OPSCORE_FASTMTC_CBR_CMW","USP_OPSCORE_FASTMTC_CBR_CMG",
"USP_OPSCORE_FASTMTC_CBR_CMWSG","USP_OPSCORE_FASTMTC_CBR_CMWTG","USP_OPSCORE_FASTMTC_CBR_CMSW","USP_OPSCORE_FASTMTC_CBR_CSW","USP_OPSCORE_FASTMTC_MCD_C","USP_OPSCORE_FASTMTC_MCD_CM","USP_OPSCORE_FASTMTC_MCD_CMW",
"USP_OPSCORE_FASTMTC_MCD_CMG","USP_OPSCORE_FASTMTC_MCD_CMWSG","USP_OPSCORE_FASTMTC_MCD_CMWTG","USP_OPSCORE_FASTMTC_MCD_CMSW","USP_OPSCORE_FASTMTC_RGR_C","USP_OPSCORE_FASTMTC_RGR_CM",
"USP_OPSCORE_FASTMTC_RGR_CMW","USP_OPSCORE_FASTMTC_RGR_CMG","USP_OPSCORE_FASTMTC_RGR_CMWSG","USP_OPSCORE_FASTMTC_RGR_CMWTG","USP_OPSCORE_FASTMTC_RGR_CMSW","USP_OPSCORE_FASTMTC_RGR_CSW",
"USP_OPS_FASTXP_BLK_MC_01","USP_OPS_FASTXP_BLK_MC_02","USP_OPS_FASTXP_BLK_MC_03","USP_OPS_FASTXP_BLK_MC_04","USP_OPS_FASTXP_BLK_MC_05",
"USP_OPS_FASTXP_BLK_MC_06","USP_OPS_FASTXP_BLK_MC_07","USP_OPS_FASTXP_BLK_MC_08","USP_OPS_FASTXP_TAN_MC_01",
"USP_OPS_FASTXP_TAN_MC_02","USP_OPS_FASTXP_TAN_MC_03","USP_OPS_FASTXP_TAN_MC_04","USP_OPS_FASTXP_TAN_MC_05",
"USP_OPS_FASTXP_TAN_MC_06","USP_OPS_FASTXP_TAN_MC_07","USP_OPS_FASTXP_TAN_MC_08"];

titan_jtp_helm = ["USP_OPSCORE_FASTMTC_DCU_C", "USP_OPSCORE_FASTMTC_DCU_CM", "USP_OPSCORE_FASTMTC_DCU_CMW", "USP_OPSCORE_FASTMTC_DCU_CMG", "USP_OPSCORE_FASTMTC_DCU_CMWSG", "USP_OPSCORE_FASTMTC_DCU_CMWTG",
"USP_OPSCORE_FASTMTC_DCU_CMSW", "USP_OPSCORE_FASTMTC_DCU_CSW","USP_OPSCORE_FASTMTC_M81_C", "USP_OPSCORE_FASTMTC_M81_CM", "USP_OPSCORE_FASTMTC_M81_CMW", "USP_OPSCORE_FASTMTC_M81_CMG",
"USP_OPSCORE_FASTMTC_M81_CMWSG", "USP_OPSCORE_FASTMTC_M81_CMWTG", "USP_OPSCORE_FASTMTC_M81_CMSW", "USP_OPSCORE_FASTMTC_M81_CSW","USP_OPSCORE_FASTMTC_RGR_C", "USP_OPSCORE_FASTMTC_RGR_CM",
"USP_OPSCORE_FASTMTC_RGR_CMW", "USP_OPSCORE_FASTMTC_RGR_CMG", "USP_OPSCORE_FASTMTC_RGR_CMWSG", "USP_OPSCORE_FASTMTC_RGR_CMWTG", "USP_OPSCORE_FASTMTC_RGR_CMSW", "USP_OPSCORE_FASTMTC_RGR_CSW","USP_OPS_FASTXP_CT_FG"];

titan_wtp_helm = ["USP_OPSCORE_FASTMTC_KTYETI_C", "USP_OPSCORE_FASTMTC_KTYETI_CM", "USP_OPSCORE_FASTMTC_KTYETI_CMW", "USP_OPSCORE_FASTMTC_KTYETI_CMG", "USP_OPSCORE_FASTMTC_KTYETI_CMWSG",
"USP_OPSCORE_FASTMTC_KTYETI_CMWTG", "USP_OPSCORE_FASTMTC_KTYETI_CMSW", "USP_OPSCORE_FASTMTC_KTYETI_CSW",
"USP_OPSCORE_FASTMTC_MCA_C", "USP_OPSCORE_FASTMTC_MCA_CM", "USP_OPSCORE_FASTMTC_MCA_CMW", "USP_OPSCORE_FASTMTC_MCA_CMG", "USP_OPSCORE_FASTMTC_MCA_CMWSG", "USP_OPSCORE_FASTMTC_MCA_CMWTG",
"USP_OPSCORE_FASTMTC_MCA_CMSW", "USP_OPSCORE_FASTMTC_MCA_CSW",
"USP_OPSCORE_FASTMTC_TROPENTARN_C", "USP_OPSCORE_FASTMTC_TROPENTARN_CM", "USP_OPSCORE_FASTMTC_TROPENTARN_CMW", "USP_OPSCORE_FASTMTC_TROPENTARN_CMG", "USP_OPSCORE_FASTMTC_TROPENTARN_CMWSG",
"USP_OPSCORE_FASTMTC_TROPENTARN_CMWTG", "USP_OPSCORE_FASTMTC_TROPENTARN_CMSW", "USP_OPSCORE_FASTMTC_TROPENTARN_CSW"];

titan_mtp_brille = ["G_lowprofile","G_Combat_Goggles_tna_F","G_Combat","G_Balaclava_TI_G_blk_F","G_Balaclava_TI_blk_F","G_Balaclava_lowprofile","G_Balaclava_combat","G_Balaclava_blk",
"USP_SHEMAGH_RGR","USP_SHEMAGH_CBR","USP_SHEMAGH_BLK","USP_SHEMAGH2_RGR","USP_SHEMAGH2_CBR","USP_SHEMAGH2_BLK","USP_SHEMAGH4_RGR","USP_SHEMAGH4_CBR",
"USP_SHEMAGH4_BLK","USP_SHEMAGH5_RGR","USP_SHEMAGH5_CBR","USP_SHEMAGH5_BLK","USP_OAKLEY_SI2","USP_OAKLEY_SI2_BLK","USP_OAKLEY_SI2_EMB","USP_OAKLEY_SI2_YEL",
"USP_OAKLEY_SI2_MC","USP_OAKLEY_SI2_MC_BLK","USP_OAKLEY_SI2_MC_EMB","USP_OAKLEY_SI2_MC_YEL","USP_OAKLEY_SI2_TAN","USP_OAKLEY_SI2_TAN_BLK","USP_OAKLEY_SI2_TAN_EMB","USP_OAKLEY_SI2_TAN_YEL",
"USP_DETCORD","USP_DETCORD2","USP_DETCORD3","USP_DETCORD4","USP_DETCORD_GRN","USP_DETCORD_GRN2","USP_DETCORD_MC","USP_DETCORD_TAN",
"USP_BALACLAVA","USP_BALACLAVA_CBR","USP_BALACLAVA_MC","USP_BALACLAVA_RGR","USP_BALACLAVA2","USP_BALACLAVA2_CBR","USP_BALACLAVA2_MC","USP_BALACLAVA2_RGR"];

titan_jtp_brille = ["G_lowprofile", "G_Combat_Goggles_tna_F", "G_Combat",
"G_Balaclava_TI_G_tna_F", "G_Balaclava_TI_tna_F", "G_Balaclava_TI_G_blk_F", "G_Balaclava_TI_blk_F", "G_Balaclava_lowprofile",  "G_Balaclava_combat", "G_Balaclava_blk",
"USP_SHEMAGH_RGR", "USP_SHEMAGH_CBR", "USP_SHEMAGH_BLK","USP_SHEMAGH2_RGR", "USP_SHEMAGH2_CBR", "USP_SHEMAGH2_BLK",
"USP_SHEMAGH4_RGR", "USP_SHEMAGH4_CBR", "USP_SHEMAGH4_BLK","USP_SHEMAGH5_RGR", "USP_SHEMAGH5_CBR", "USP_SHEMAGH5_BLK",
"USP_OAKLEY_SI2", "USP_OAKLEY_SI2_BLK", "USP_OAKLEY_SI2_EMB", "USP_OAKLEY_SI2_YEL",
"USP_OAKLEY_SI2_TAN", "USP_OAKLEY_SI2_TAN_BLK", "USP_OAKLEY_SI2_TAN_EMB", "USP_OAKLEY_SI2_TAN_YEL","USP_DETCORD", "USP_DETCORD2", "USP_DETCORD3", "USP_DETCORD4","USP_DETCORD_GRN", "USP_DETCORD_GRN2",
"USP_DETCORD_MC", "USP_DETCORD_TAN","USP_BALACLAVA", "USP_BALACLAVA_CBR", "USP_BALACLAVA_MC", "USP_BALACLAVA_RGR", "USP_BALACLAVA2", "USP_BALACLAVA2_CBR", "USP_BALACLAVA2_MC", "USP_BALACLAVA2_RGR"];

titan_wtp_brille = ["G_lowprofile", "G_Combat","G_Balaclava_lowprofile",  "G_Balaclava_Combat", "G_Balaclava_BLK","USP_SHEMAGH", "USP_SHEMAGH_BLK",
"USP_SHEMAGH2", "USP_SHEMAGH2_BLK","USP_SHEMAGH4", "USP_SHEMAGH4_BLK","USP_SHEMAGH5", "USP_SHEMAGH5_BLK","USP_OAKLEY_SI2", "USP_OAKLEY_SI2_BLK", "USP_OAKLEY_SI2_EMB", "USP_OAKLEY_SI2_YEL",
"USP_DETCORD", "USP_DETCORD2", "USP_DETCORD3", "USP_DETCORD4","USP_DETCORD_GRN", "USP_DETCORD_GRN2","USP_DETCORD_MC", "USP_DETCORD_TAN", "USP_BALACLAVA_GRY", "USP_BALACLAVA_WHT", "USP_BALACLAVA2_GRY", "USP_BALACLAVA2_WHT"
];
